from aledb_common.util import GENE_RANGE_ANNOTATION_DELIMITER, INTRAGENIC_LEFT_CHAR, INTRAGENIC_RIGHT_CHAR, get_gene_list  # noqa: F401

INTERGENIC_SPLIT_CHAR = '/'
BRESEQ_GENE_RANGE_CHAR = '–'  # TODO: this char is a different encoding; currently don't know how to normalize all encoding.


def get_annotated_gene_list(breseq_mutation_gene_annotation, breseq_gene_product_annotation=None):
    """
    To be used when populating the aledb_seq.models.mutation.gene field
    while integrating mutations from static ALE data.
    :param mutation_gene_str: gene annotation string generated by breseq
    :return: list of explicit genes implied by mutation_gene_str
    """
    mutation_gene_str = _get_str_from_annotation(breseq_mutation_gene_annotation)

    if breseq_gene_product_annotation is not None:
        gene_product_str = _get_str_from_annotation(breseq_gene_product_annotation)
    else:
        gene_product_str = None

    if mutation_gene_str is not None:
        if INTERGENIC_SPLIT_CHAR in mutation_gene_str:
            gene_list = mutation_gene_str.split(INTERGENIC_SPLIT_CHAR)
        elif BRESEQ_GENE_RANGE_CHAR in mutation_gene_str:
            gene_list = _get_gene_list_from_range(gene_product_str)
        else:
            gene_list = [mutation_gene_str]
    else:
        gene_list = []

    return gene_list


def _get_str_from_annotation(annotation):
    try:
        annot = annotation.decode("utf-8")
    except AttributeError:
        annot = annotation
    return str(annot)


def _get_gene_list_from_range(gene_product_str):
    return gene_product_str.split(GENE_RANGE_ANNOTATION_DELIMITER)


