# Generated by Django 6.1.1 on 2026-09-04 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aledb_experiment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gff3_sha256', models.CharField(max_length=64)),
                ('fasta_sha256', models.CharField(max_length=64)),
                ('sequence_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('seq_ids', models.JSONField(default=list)),
                ('total_length', models.BigIntegerField(default=0)),
                ('experiment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reference', to='aledb_experiment.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Mutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutation_type', models.CharField(help_text='Use breseq mutation codes, see the genome diff site\n                                     on the barrick lab wiki (http://tinyurl.com/l3fvnap) for more\n                                     information', max_length=3, null=True)),
                ('position', models.IntegerField()),
                ('feature_length', models.IntegerField(blank=True, null=True)),
                ('sequence_change', models.CharField(max_length=200)),
                ('protein_change', models.CharField(default='', max_length=300)),
                ('gene', models.CharField(blank=True, max_length=19000, null=True)),
                ('product', models.TextField(default='', null=True)),
                ('reseq_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('tags', models.CharField(blank=True, max_length=500, null=True)),
                ('snp_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('mutation_category', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('gene_name', models.TextField(blank=True, null=True)),
                ('locus_tag', models.TextField(blank=True, null=True)),
                ('start_position', models.IntegerField(blank=True, null=True)),
                ('end_position', models.IntegerField(blank=True, null=True)),
                ('annotation', models.JSONField(blank=True, null=True)),
                ('gd_data', models.JSONField(blank=True, null=True)),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mutations', to='aledb_experiment.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='NcbiSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('length', models.BigIntegerField()),
                ('accession', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('unchecked', 'Not checked'), ('verified', 'Verified against NCBI'), ('mismatch', 'Sequence does not match'), ('not_found', 'No such NCBI record'), ('error', 'Check failed')], default='unchecked', max_length=16)),
                ('detail', models.TextField(blank=True, default='')),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NCBI sequence',
                'verbose_name_plural': 'NCBI sequences',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='1', max_length=100)),
                ('is_clonal', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('reference_genome', models.CharField(blank=True, max_length=200, null=True)),
                ('sequencing_date', models.CharField(blank=True, max_length=200, null=True)),
                ('breseq_version', models.CharField(blank=True, max_length=200, null=True)),
                ('library_prep', models.CharField(blank=True, max_length=200, null=True)),
                ('tags', models.CharField(blank=True, max_length=500, null=True)),
                ('medium_description', models.CharField(blank=True, max_length=500, null=True)),
                ('person', models.CharField(blank=True, max_length=200)),
                ('source_name', models.CharField(blank=True, max_length=200, null=True)),
                ('reads', models.IntegerField(blank=True, default=0)),
                ('average_read_length', models.FloatField(blank=True, default=0)),
                ('mean_coverage', models.FloatField(blank=True, default=0)),
                ('percentage_mapped', models.FloatField(blank=True, default=0)),
                ('bam_stored', models.BooleanField(default=False)),
                ('coverage_stored', models.BooleanField(default=False)),
                ('time_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aledb_experiment.timepoint')),
            ],
        ),
        migrations.CreateModel(
            name='MutationCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(null=True)),
                ('wt_reads', models.IntegerField(null=True)),
                ('mutated_reads', models.IntegerField(null=True)),
                ('other_reads', models.IntegerField(null=True)),
                ('reference_genome_likelihood', models.FloatField(null=True)),
                ('frequency', models.DecimalField(decimal_places=4, max_digits=5, null=True)),
                ('source', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aledb_seq.mutation')),
                ('sample', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aledb_seq.sample')),
            ],
        ),
        migrations.CreateModel(
            name='UncalledRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_id', models.CharField(max_length=100)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aledb_seq.sample')),
            ],
            options={
                'verbose_name_plural': 'uncalled regions',
            },
        ),
    ]
