# Generated by Django 4.2.30 on 2026-06-26 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aledb_experiment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mutation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutation_type', models.CharField(help_text='Use breseq mutation codes, see the genome diff site\n                                     on the barrick lab wiki (http://tinyurl.com/l3fvnap) for more\n                                     information', max_length=3, null=True)),
                ('position', models.IntegerField()),
                ('feature_length', models.IntegerField(blank=True, null=True)),
                ('sequence_change', models.CharField(max_length=200)),
                ('protein_change', models.CharField(default='', max_length=300)),
                ('gene', models.CharField(blank=True, max_length=19000, null=True)),
                ('product', models.TextField(default='', null=True)),
                ('function', models.CharField(default='', max_length=500, null=True)),
                ('go_process', models.CharField(default='', max_length=300, null=True)),
                ('go_component', models.CharField(default='', max_length=300, null=True)),
                ('reseq_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('tags', models.CharField(blank=True, max_length=500, null=True)),
                ('reference_error', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ObservedMutation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(null=True)),
                ('breseq_present', models.BooleanField(null=True)),
                ('gatk_present', models.BooleanField(null=True)),
                ('wt_reads', models.IntegerField(null=True)),
                ('mutated_reads', models.IntegerField(null=True)),
                ('other_reads', models.IntegerField(null=True)),
                ('reference_genome_likelihood', models.FloatField(null=True)),
                ('evidence', models.CharField(blank=True, max_length=400, null=True)),
                ('gatk_evidence', models.CharField(blank=True, max_length=400, null=True)),
                ('frequency', models.DecimalField(decimal_places=4, max_digits=5, null=True)),
                ('frequency_gatk', models.DecimalField(decimal_places=4, max_digits=5, null=True)),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aledb_seq.mutation')),
            ],
        ),
        migrations.CreateModel(
            name='ResequencingExperiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(blank=True, max_length=200)),
                ('reads', models.IntegerField(blank=True, default=0)),
                ('average_read_length', models.FloatField(blank=True, default=0)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('experiment_location', models.CharField(blank=True, max_length=200, null=True)),
                ('gatk_location', models.CharField(blank=True, max_length=200, null=True)),
                ('sample_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mean_coverage', models.FloatField(blank=True, default=0)),
                ('percentage_mapped', models.FloatField(blank=True, default=0)),
                ('mutations', models.ManyToManyField(through='aledb_seq.ObservedMutation', to='aledb_seq.mutation')),
                ('tech_rep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aledb_experiment.technicalreplicate')),
            ],
        ),
        migrations.CreateModel(
            name='UnassignedMissingCoverageEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reads_left_url', models.CharField(blank=True, max_length=500, null=True)),
                ('reads_right_url', models.CharField(blank=True, max_length=500, null=True)),
                ('coverage', models.CharField(blank=True, max_length=500, null=True)),
                ('seq_id', models.CharField(max_length=100)),
                ('start', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=200)),
                ('reads_left', models.CharField(blank=True, max_length=100, null=True)),
                ('reads_right', models.CharField(blank=True, max_length=100, null=True)),
                ('gene', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('sequencing_experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aledb_seq.resequencingexperiment')),
            ],
        ),
        migrations.AddField(
            model_name='observedmutation',
            name='sequencing_experiment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aledb_seq.resequencingexperiment'),
        ),
    ]
