# Generated by Django 4.2.30 on 2026-07-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aledb_seq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutation',
            name='gd_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
