# Generated by Django 4.2.30 on 2026-08-21 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aledb_experiment', '0001_initial'),
        ('aledb_seq', '0002_mutation_gd_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='resequencingexperiment',
            name='bam_stored',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ExperimentReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gff3_sha256', models.CharField(max_length=64)),
                ('fasta_sha256', models.CharField(max_length=64)),
                ('seq_ids', models.JSONField(default=list)),
                ('total_length', models.BigIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ale_experiment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reference', to='aledb_experiment.aleexperiment')),
            ],
        ),
    ]
