# Generated by Django 4.2.30 on 2026-08-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aledb_seq', '0006_backfill_mutation_ale_experiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='resequencingexperiment',
            name='coverage_stored',
            field=models.BooleanField(default=False),
        ),
    ]
