# Generated by Django 4.2.30 on 2026-08-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aledb_seq', '0007_resequencingexperiment_coverage_stored'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentreference',
            name='sequence_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
