"""Drop `frequency_gatk`, the GATK half of a merge no import path has ever written.

Measured before removing it: 0 of 74,859 observations carried a value, so there is nothing to
carry into `frequency` and no backfill to run.

It was not merely unused. `aledb_filter.util` ANDed a `frequency_gatk__lt` term into the
exclusion whenever `min_gatk_cutoff` was set -- which was always, by default -- and a
comparison against null is never true, so the whole clause was unsatisfiable and the
experiment frequency cutoff excluded nothing at all.
"""


# Generated by Django 4.2.30 on 2026-08-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aledb_seq', '0010_drop_caller_present_flags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observedmutation',
            name='frequency_gatk',
        ),
    ]
