# Generated by Django 4.2.30 on 2026-08-30 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aledb_seq', '0012_cap_recorded_gene_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='NcbiSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('length', models.BigIntegerField()),
                ('accession', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('unchecked', 'Not checked'), ('verified', 'Verified against NCBI'), ('mismatch', 'Sequence does not match'), ('not_found', 'No such NCBI record'), ('error', 'Check failed')], default='unchecked', max_length=16)),
                ('detail', models.TextField(blank=True, default='')),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NCBI sequence',
                'verbose_name_plural': 'NCBI sequences',
            },
        ),
    ]
