# Generated by Django 6.1.1 on 2026-09-04 12:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aledb_experiment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLock',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('holder', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('open', 'Open'), ('finalized', 'Finalized'), ('failed', 'Failed')], default='open', max_length=16)),
                ('import_type', models.CharField(blank=True, max_length=64)),
                ('manifest', models.JSONField(default=list)),
                ('declared_bytes', models.BigIntegerField(default=0)),
                ('received_bytes', models.BigIntegerField(default=0)),
                ('progress', models.JSONField(blank=True, default=dict)),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aledb_experiment.experiment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
