# Generated by Django 4.2.30 on 2026-08-21 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('open', 'Open'), ('finalized', 'Finalized'), ('failed', 'Failed')], default='open', max_length=16)),
                ('project_name', models.CharField(max_length=200)),
                ('experiment_name', models.CharField(max_length=200)),
                ('person', models.CharField(blank=True, max_length=200)),
                ('manifest', models.JSONField(default=list)),
                ('declared_bytes', models.BigIntegerField(default=0)),
                ('received_bytes', models.BigIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
