# Generated by Django 4.2.30 on 2026-08-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aledb_import', '0002_remove_uploadsession_experiment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='progress',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
