# Generated by Django 4.2.30 on 2026-08-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aledb_import', '0003_uploadsession_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLock',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('holder', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
