# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-30 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seq', '0015_auto_20171005_0807'),
        ('ale', '0017_auto_20161116_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvergeMutation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ale_experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ale.AleExperiment')),
                ('mutation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seq.Mutation')),
            ],
        ),
    ]
