# Generated by Django 4.2.30 on 2026-08-26 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aledb_experiment', '0003_backfill_view_project_grants'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivedDataState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='the name the rebuilder is registered under', max_length=100)),
                ('stale_since', models.DateTimeField(blank=True, db_index=True, help_text='NULL means current', null=True)),
                ('rebuilt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('ale_experiment', models.ForeignKey(blank=True, help_text='NULL for a site-scoped rebuild', null=True, on_delete=django.db.models.deletion.CASCADE, to='aledb_experiment.aleexperiment')),
            ],
            options={
                'verbose_name': 'derived data state',
                'verbose_name_plural': 'derived data states',
            },
        ),
        migrations.AddConstraint(
            model_name='deriveddatastate',
            constraint=models.UniqueConstraint(fields=('name', 'ale_experiment'), name='one_state_per_rebuild_per_experiment'),
        ),
        migrations.AddConstraint(
            model_name='deriveddatastate',
            constraint=models.UniqueConstraint(condition=models.Q(('ale_experiment__isnull', True)), fields=('name',), name='one_state_per_site_scoped_rebuild'),
        ),
    ]
