# Generated by Django 6.1.1 on 2026-09-04 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aledb_common', '0001_initial'),
        ('aledb_experiment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deriveddatastate',
            name='experiment',
            field=models.ForeignKey(blank=True, help_text='NULL for a site-scoped rebuild', null=True, on_delete=django.db.models.deletion.CASCADE, to='aledb_experiment.experiment'),
        ),
        migrations.AddConstraint(
            model_name='deriveddatastate',
            constraint=models.UniqueConstraint(fields=('name', 'experiment'), name='one_state_per_rebuild_per_experiment'),
        ),
        migrations.AddConstraint(
            model_name='deriveddatastate',
            constraint=models.UniqueConstraint(condition=models.Q(('experiment__isnull', True)), fields=('name',), name='one_state_per_site_scoped_rebuild'),
        ),
    ]
