version: "3"
services:
  redis:
    container_name: aledb-redis
    image: redis
    #network_mode: "host"
    ports:
      - 6379:6379
  web:
    container_name: aledb-web
    build: .
    #image: aledb_web
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - .docker/one.env
    volumes:
      - .:/app
      - /data/aledata:/data/aledata
      - /home/muyao/.ssh:/root/.ssh

    command: bash -c "python manage.py collectstatic --no-input && daphne -b 0.0.0.0 -p 8000 aleinfo.asgi:application"
    ports:
      - 8000:8000
volumes:
  static:
