version: "3"
services:
  redis:
    container_name: aledb-redis
    image: redis
    ports:
      - 6379:6379
  web:
    container_name: aledb-web
    build: .
    #image: aledb_web
    env_file:
      - .docker/one.env
    volumes:
      - .:/app
      - /data/aledata:/data/aledata
      - /home/muyao/.ssh:/root/.ssh
      - /var/run/mysqld/mysqld.sock:/run/mysqld/mysqld.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"

    command: bash -c "python manage.py collectstatic --no-input && daphne -b 0.0.0.0 -p 80 aleinfo.asgi:application"
  nginx:
    container_name: aledb-nginx
    image: nginx
    links:
      - web
    depends_on:
      - web
    volumes:
      - static:/usr/share/nginx/static:ro
      - ./nginx-ws.conf:/etc/nginx/conf.d/default.conf:ro
      - /data/aledata:/data/aledata:ro
    command: [ nginx-debug, '-g', 'daemon off;' ]
    ports:
      - 8000:80
volumes:
  static:
