version: "2"
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=composetest
      - MYSQL_PASSWORD=testpassword
      - MYSQL_DATABASE=composetest
  web:
    build: .
    command: "./docker-runserver.sh"
    environment:
      - DEBUG=1
      - DJANGO_SERVER_HOST=localhost
      - MYSQL_USER=composetest
      - MYSQL_PASSWORD=testpassword
      - MYSQL_DATABASE=composetest
    ports:
      - "8000:80"
    links:
      - db
    depends_on:
      - db
