# Generated by Django 6.1.1 on 2026-09-06 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mutint_common', '0001_initial'),
        ('mutint_experiment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deriveddatastate',
            name='experiment',
            field=models.ForeignKey(blank=True, help_text='NULL for a site-scoped rebuild', null=True, on_delete=django.db.models.deletion.CASCADE, to='mutint_experiment.experiment'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='deriveddatastate',
            constraint=models.UniqueConstraint(fields=('name', 'experiment'), name='one_state_per_rebuild_per_experiment'),
        ),
        migrations.AddConstraint(
            model_name='deriveddatastate',
            constraint=models.UniqueConstraint(condition=models.Q(('experiment__isnull', True)), fields=('name',), name='one_state_per_site_scoped_rebuild'),
        ),
        migrations.AddConstraint(
            model_name='userpreference',
            constraint=models.UniqueConstraint(fields=('user', 'key'), name='one_preference_per_user_per_key'),
        ),
    ]
