# Generated by Django 6.1.1 on 2026-09-12 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutint_common', '0002_initial'),
        ('mutint_experiment', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, help_text='the key the kind is registered under', max_length=64)),
                ('bytes', models.BigIntegerField(default=0)),
                ('measured_at', models.DateTimeField()),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_usage', to='mutint_experiment.experiment')),
            ],
            options={
                'verbose_name': 'storage usage',
                'verbose_name_plural': 'storage usage',
                'constraints': [models.UniqueConstraint(fields=('experiment', 'kind'), name='one_storage_row_per_experiment_per_kind')],
            },
        ),
    ]
