# Generated by Django 6.1.1 on 2026-09-06 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutint_common', '0003_userpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='updated_at',
        ),
    ]
