# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seq', '0002_auto_20151114_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_cutoff', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
