# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seq', '0003_auto_20160705_0803'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneToPDB',
        ),
    ]
