# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-15 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0014_technicalreplicate'),
        ('seq', '0004_delete_genetopdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resequencingexperiment',
            name='isolate',
        ),
        migrations.AddField(
            model_name='mutation',
            name='function',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mutation',
            name='go_component',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='mutation',
            name='go_process',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='mutation',
            name='product',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mutation',
            name='reseq_reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resequencingexperiment',
            name='tech_rep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ale.TechnicalReplicate'),
        ),
    ]
