# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seq', '0004_auto_20160306_1349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
