# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-31 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seq', '0005_auto_20160815_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='unassignedmissingcoverageevidence',
            name='coverage',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='unassignedmissingcoverageevidence',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='unassignedmissingcoverageevidence',
            name='gene',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='unassignedmissingcoverageevidence',
            name='reads_left',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unassignedmissingcoverageevidence',
            name='reads_left_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='unassignedmissingcoverageevidence',
            name='reads_right',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unassignedmissingcoverageevidence',
            name='reads_right_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='unassignedmissingcoverageevidence',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]