# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-31 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seq', '0007_auto_20160831_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unassignedmissingcoverageevidence',
            name='end',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unassignedmissingcoverageevidence',
            name='size',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='unassignedmissingcoverageevidence',
            name='start',
            field=models.CharField(max_length=100),
        ),
    ]
