# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-12 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seq', '0008_auto_20160831_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observedmutation',
            name='sequencing_experiment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seq.ResequencingExperiment'),
        ),
    ]
