# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-12 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seq', '0009_auto_20160911_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutation',
            name='gene',
            field=models.CharField(blank=True, max_length=19000, null=True),
        ),
    ]
