# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-10 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seq', '0010_auto_20160912_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutation',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
