# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seq', '0011_mutation_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutation',
            name='sequence_change',
            field=models.CharField(max_length=200),
        ),
    ]
