# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seq', '0012_auto_20170305_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutation',
            name='protein_change',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='resequencingexperiment',
            name='average_read_length',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='resequencingexperiment',
            name='mean_coverage',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='resequencingexperiment',
            name='percentage_mapped',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='resequencingexperiment',
            name='reads',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
