# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-25 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seq', '0013_auto_20170723_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutation',
            name='product',
            field=models.TextField(default='', max_length=1500, null=True),
        ),
    ]
