# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-05 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seq', '0014_auto_20170925_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutation',
            name='product',
            field=models.TextField(default='', null=True),
        ),
    ]
