# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-22 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seq', '0015_auto_20171005_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observedmutation',
            name='mutation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seq.Mutation'),
        ),
    ]
