# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-09-01 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seq', '0016_auto_20190522_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='observedmutation',
            name='frequency_gatk',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
    ]
