# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-08-16 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seq', '0017_observedmutation_frequency_gatk'),
    ]

    operations = [
        migrations.AddField(
            model_name='observedmutation',
            name='gatk_evidence',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='observedmutation',
            name='gatk_present',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='resequencingexperiment',
            name='experiment_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resequencingexperiment',
            name='gatk_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resequencingexperiment',
            name='sample_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
