# Generated by Django 6.1.1 on 2026-09-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutint_import', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='consumer',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='state',
            field=models.CharField(choices=[('open', 'Open'), ('finalized', 'Finalized'), ('failed', 'Failed'), ('claimed', 'Claimed')], default='open', max_length=16),
        ),
    ]
