# Generated by Django 6.1.1 on 2026-09-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutint_import', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='accessions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
