# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0006_isolate_reseq_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_cutoff', models.IntegerField(default=20)),
                ('max_cutoff', models.IntegerField(default=100)),
                ('ignored_genes', models.CharField(max_length=100)),
            ],
        ),
    ]
