# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 03:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0007_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='ignored_genes',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='filter',
            name='max_cutoff',
            field=models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='filter',
            name='min_cutoff',
            field=models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
