# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0008_auto_20160304_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoredGenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(max_length=20)),
                ('two', models.CharField(max_length=20)),
                ('three', models.CharField(max_length=20)),
                ('four', models.CharField(max_length=20)),
                ('five', models.CharField(max_length=20)),
                ('six', models.CharField(max_length=20)),
                ('seven', models.CharField(max_length=20)),
                ('eight', models.CharField(max_length=20)),
                ('nine', models.CharField(max_length=20)),
                ('ten', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='filter',
            name='ale_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ale.AleId'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='ignored_genes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ale.IgnoredGenes'),
        ),
    ]
