# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0008_auto_20160705_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='ignored_mutations',
            field=models.TextField(blank=True, default=''),
        ),
    ]
