# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0009_filter_ignored_mutations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='ale_experiment',
        ),
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
