# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0009_auto_20160306_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='ale_id',
        ),
    ]
