# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0010_remove_filter_ale_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='ignored_genes',
        ),
        migrations.DeleteModel(
            name='IgnoredGenes',
        ),
    ]
