# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0010_auto_20160712_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aleid',
            name='knockouts',
        ),
    ]
