# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0011_remove_aleid_knockouts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keymutation',
            name='ale_experiment',
        ),
        migrations.RemoveField(
            model_name='keymutation',
            name='mutation',
        ),
        migrations.DeleteModel(
            name='KeyMutation',
        ),
    ]
