# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0011_auto_20160306_1142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
