# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0012_delete_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoredGenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
