# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0012_auto_20160728_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aleexperiment',
            name='simulation',
        ),
    ]
