# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-15 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0013_remove_aleexperiment_simulation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalReplicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_rep_number', models.IntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('isolate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ale.Isolate')),
            ],
        ),
    ]
