# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0013_ignoredgenes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IgnoredGenes',
        ),
    ]
