# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0014_technicalreplicate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentExperiments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.IntegerField(null=True)),
                ('second', models.IntegerField(null=True)),
                ('third', models.IntegerField(null=True)),
                ('fourth', models.IntegerField(null=True)),
                ('fifth', models.IntegerField(null=True)),
            ],
        ),
    ]
