# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0014_delete_ignoredgenes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_cutoff', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
