# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0015_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='max_cutoff',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
