# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0016_filter_max_cutoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='ignored_genes',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
