# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0016_technicalreplicate_tags'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='isolate',
            unique_together=set([]),
        ),
    ]
