# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0017_filter_ignored_genes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='ignored_genes',
        ),
        migrations.AddField(
            model_name='filter',
            name='eight',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AddField(
            model_name='filter',
            name='five',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AddField(
            model_name='filter',
            name='four',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AddField(
            model_name='filter',
            name='nine',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AddField(
            model_name='filter',
            name='one',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AddField(
            model_name='filter',
            name='seven',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AddField(
            model_name='filter',
            name='six',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AddField(
            model_name='filter',
            name='ten',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AddField(
            model_name='filter',
            name='three',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AddField(
            model_name='filter',
            name='two',
            field=models.CharField(default=b'', max_length=20),
        ),
    ]
