# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0017_auto_20161116_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='aleexperiment',
            name='pub_ref',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aleexperiment',
            name='pub_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
