# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0018_auto_20180417_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aleexperiment',
            name='pub_ref',
        ),
        migrations.RemoveField(
            model_name='aleexperiment',
            name='pub_url',
        ),
    ]
