# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0019_auto_20180421_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aleexperiment',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
