# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-19 18:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ale', '0020_auto_20181105_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='project created date')),
                ('is_public', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('new', 'New'), ('in progress', 'In progress'), ('completed', 'Completed')], default='new', max_length=25)),
                ('user', models.ForeignKey(default=None, help_text='project owner', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete'),
                'permissions': (('view_prject', 'Can view project'),),
            },
        ),
        migrations.AddField(
            model_name='aleexperiment',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ale.Project'),
        ),
    ]
