# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-12 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0021_auto_20181119_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('view_project', 'View project'),)},
        ),
    ]
