# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-19 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0022_auto_20190211_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aleexperiment',
            options={'verbose_name_plural': 'experiments'},
        ),
    ]
