# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-09-10 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0023_auto_20190219_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='carbon_source',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='nitrogen_source',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='phosphorous_source',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='sulfur_source',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='supplement',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
