# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-13 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0024_auto_20190910_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='phosphorous_source',
            new_name='phosphorus_source',
        ),
    ]
