# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-02-26 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0025_auto_20191112_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='calcium_source',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
