# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-18 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0026_media_calcium_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='aleexperiment',
            name='doi',
            field=models.CharField(default='temp doi', max_length=200),
            preserve_default=False,
        ),
    ]
