# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-18 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0027_aleexperiment_doi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aleexperiment',
            name='doi',
            field=models.CharField(default='', max_length=200),
        ),
    ]
