# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-18 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0028_auto_20200517_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aleexperiment',
            name='doi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
