# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-18 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0029_auto_20200517_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='temperature',
            field=models.CharField(default='37', help_text='Temperature in Celcius', max_length=200),
        ),
    ]
