INTERGENIC_SPLIT_CHAR = '/'
INTRAGENIC_RIGHT_CHAR = '['
INTRAGENIC_LEFT_CHAR = ']'
BRESEQ_GENE_RANGE_CHAR = '–'  # TODO: this char is a different encoding; currently don't know how to normalize all encoding.
GENE_RANGE_ANNOTATION_DELIMITER = ", "


def get_annotated_gene_list(breseq_mutation_gene_annotation, breseq_gene_product_annotation=None):
    """
    To be used when populating the seq.models.mutation.gene field
    while integrating mutations from static ALE data.
    :param mutation_gene_str: gene annotation string generated by breseq
    :return: list of explicit genes implied by mutation_gene_str
    """
    mutation_gene_str = _get_str_from_annotation(breseq_mutation_gene_annotation)

    if breseq_gene_product_annotation is not None:
        gene_product_str = _get_str_from_annotation(breseq_gene_product_annotation)
    else:
        gene_product_str = None

    if mutation_gene_str is not None:
        if INTERGENIC_SPLIT_CHAR in str(mutation_gene_str):
            gene_list = mutation_gene_str.split(INTERGENIC_SPLIT_CHAR)
        elif BRESEQ_GENE_RANGE_CHAR in str(mutation_gene_str):
            gene_list = _get_gene_list_from_range(gene_product_str)
        else:
            gene_list = [mutation_gene_str]
    else:
        gene_list = []

    return gene_list


def _get_str_from_annotation(annotation):
    try:
        str = annotation.decode("utf-8")
    except AttributeError:
        str = annotation
    return str


def _get_gene_list_from_range(gene_product_str):
    return gene_product_str.split(GENE_RANGE_ANNOTATION_DELIMITER)


def get_gene_list(annotated_gene_list_str):
    """
    To be used when populating the enrichment.models.EnrichmentMutation table.
    Results only to be used during gene count and not to be used in annotating
    mutation entries in the DB.
    :param annotated_gene_list: list of genes
    :return: list of genes without intragenic mutation annotations
    """
    annotated_gene_list = annotated_gene_list_str.split(GENE_RANGE_ANNOTATION_DELIMITER)
    clean_gene_list = []
    for gene_idx in range(len(annotated_gene_list)):
        gene = annotated_gene_list[gene_idx]
        if INTRAGENIC_LEFT_CHAR in gene:
            gene = gene.replace(INTRAGENIC_LEFT_CHAR, '')
        if INTRAGENIC_RIGHT_CHAR in gene:
            gene = gene.replace(INTRAGENIC_RIGHT_CHAR, '')
        clean_gene_list.append(gene)
    return clean_gene_list