INTERGENIC_SPLIT_CHAR = '/'
INTRAGENIC_RIGHT_CHAR = '['
INTRAGENIC_LEFT_CHAR = ']'


# TODO: unit testable
# TODO: add populating of gene list from a range here. Likely will have to add argument for ref file path.
def get_gene_list(mutation_gene_str):
    """
    To be used when populating the seq.models.mutation.gene field
    while integrating mutations from static ALE data.
    :param mutation_gene_str: gene annotation string generated by breseq
    :return: list of explicit genes implied by mutation_gene_str
    """
    if INTERGENIC_SPLIT_CHAR in mutation_gene_str:
        gene_list = mutation_gene_str.split(INTERGENIC_SPLIT_CHAR)
    # TODO: condition to understand if mutation_gene_str indicates a gene range
    else:
        gene_list = [mutation_gene_str]

    return gene_list

# TODO: Likely will have to add argument for ref file path.
def _get_gene_list_from_range(mutation_gene_str):
    return []


def get_clean_gene_list(gene_list):
    """
    To be used when populating the enrichment.models.EnrichmentMutation table.
    Results only to be used during gene count and not to be used in annotating
    mutation entries in the DB.
    :param gene_list: list of genes
    :return: list of genes without intragenic mutation annotations
    """
    clean_gene_list = []
    for gene_idx in range(len(gene_list)):
        gene = gene_list[gene_idx]
        if INTRAGENIC_LEFT_CHAR in gene:
            gene = gene.replace(INTRAGENIC_LEFT_CHAR, '')
        if INTRAGENIC_RIGHT_CHAR in gene:
            gene = gene.replace(INTRAGENIC_RIGHT_CHAR, '')
        clean_gene_list.append(gene)
    return clean_gene_list