INTERGENIC_SPLIT_CHAR = '/'
INTRAGENIC_RIGHT_CHAR = '['
INTRAGENIC_LEFT_CHAR = ']'
GENE_RANGE_CHAR = '–'


def get_gene_list(mutation_gene_str, ref_gene_list):
    """
    To be used when populating the seq.models.mutation.gene field
    while integrating mutations from static ALE data.
    :param mutation_gene_str: gene annotation string generated by breseq
    :return: list of explicit genes implied by mutation_gene_str
    """
    if INTERGENIC_SPLIT_CHAR in mutation_gene_str:
        gene_list = mutation_gene_str.split(INTERGENIC_SPLIT_CHAR)
    elif GENE_RANGE_CHAR in mutation_gene_str:
        gene_list = _get_gene_list_from_range(mutation_gene_str, ref_gene_list)
    else:
        gene_list = [mutation_gene_str]

    return gene_list


def _get_gene_list_from_range(mutation_gene_str, ref_gene_list):
    mutation_gene_range_list = mutation_gene_str.split(GENE_RANGE_CHAR)
    cleaned_mutation_gene_range_list = get_clean_gene_list(mutation_gene_range_list)
    start_gene_index = ref_gene_list.index(cleaned_mutation_gene_range_list[0])
    end_gene_index = ref_gene_list.index(cleaned_mutation_gene_range_list[1])
    range_gene_list = ref_gene_list[start_gene_index:end_gene_index + 1]
    if INTRAGENIC_RIGHT_CHAR in mutation_gene_range_list[0]:
        range_gene_list[0] = mutation_gene_range_list[0]
    if INTRAGENIC_RIGHT_CHAR in mutation_gene_range_list[1]:
        range_gene_list[1] = mutation_gene_range_list[-1]
    return range_gene_list


def get_clean_gene_list(gene_list):
    """
    To be used when populating the enrichment.models.EnrichmentMutation table.
    Results only to be used during gene count and not to be used in annotating
    mutation entries in the DB.
    :param gene_list: list of genes
    :return: list of genes without intragenic mutation annotations
    """
    clean_gene_list = []
    for gene_idx in range(len(gene_list)):
        gene = gene_list[gene_idx]
        if INTRAGENIC_LEFT_CHAR in gene:
            gene = gene.replace(INTRAGENIC_LEFT_CHAR, '')
        if INTRAGENIC_RIGHT_CHAR in gene:
            gene = gene.replace(INTRAGENIC_RIGHT_CHAR, '')
        clean_gene_list.append(gene)
    return clean_gene_list