# Generated by Django 6.1.1 on 2026-09-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutint_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='annotates_reference',
            field=models.BooleanField(default=False),
        ),
    ]
