# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-23 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mut_needle_data', django_mysql.models.JSONField(default=dict)),
                ('histogram_data', django_mysql.models.JSONField(default=dict)),
            ],
        ),
    ]
