# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-01 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObservedMutationCounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_base_substitution', models.IntegerField(default=0)),
                ('multiple_base_substitution', models.IntegerField(default=0)),
                ('deletion', models.IntegerField(default=0)),
                ('insertion', models.IntegerField(default=0)),
                ('mobile_element_insertion', models.IntegerField(default=0)),
                ('amplification', models.IntegerField(default=0)),
                ('duplication', models.IntegerField(default=0)),
                ('gene_conversion', models.IntegerField(default=0)),
                ('inversion', models.IntegerField(default=0)),
                ('intergenic', models.IntegerField(default=0)),
                ('noncoding', models.IntegerField(default=0)),
                ('pseudogene', models.IntegerField(default=0)),
                ('synonymous', models.IntegerField(default=0)),
                ('nonsynonymous', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueMutationCounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_base_substitution', models.IntegerField(default=0)),
                ('multiple_base_substitution', models.IntegerField(default=0)),
                ('deletion', models.IntegerField(default=0)),
                ('insertion', models.IntegerField(default=0)),
                ('mobile_element_insertion', models.IntegerField(default=0)),
                ('amplification', models.IntegerField(default=0)),
                ('duplication', models.IntegerField(default=0)),
                ('gene_conversion', models.IntegerField(default=0)),
                ('inversion', models.IntegerField(default=0)),
                ('intergenic', models.IntegerField(default=0)),
                ('noncoding', models.IntegerField(default=0)),
                ('pseudogene', models.IntegerField(default=0)),
                ('synonymous', models.IntegerField(default=0)),
                ('nonsynonymous', models.IntegerField(default=0)),
            ],
        ),
    ]
