# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-01 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observedmutationcounts',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uniquemutationcounts',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
