# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-14 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170331_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('icon', models.CharField(max_length=200)),
                ('color', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
