# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_timelineevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleCounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ale_count', models.IntegerField(default=0)),
                ('isolate_count', models.IntegerField(default=0)),
            ],
        ),
    ]
