# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-04 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_samplecounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplecounts',
            name='flask_count',
            field=models.IntegerField(default=0),
        ),
    ]
