# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 18:43
from __future__ import unicode_literals

import dashboard.models
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_samplecounts_flask_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarCharts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mut_gene_json', django_mysql.models.JSONField(default=dashboard.models.bar_chart_json_default)),
                ('mut_json', django_mysql.models.JSONField(default=dashboard.models.bar_chart_json_default)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
