# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-22 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20180422_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='observedmutationcounts',
            name='unannotated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uniquemutationcounts',
            name='unannotated',
            field=models.IntegerField(default=0),
        ),
    ]
