# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ale', '0010_auto_20160712_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_cutoff', models.PositiveSmallIntegerField(default=20)),
                ('max_cutoff', models.PositiveSmallIntegerField(default=100)),
                ('ignored_genes', models.CharField(blank=True, default='', max_length=500)),
                ('ignored_mutations', models.TextField(blank=True, default='')),
                ('ale_experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ale.AleExperiment')),
            ],
        ),
    ]
