# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-16 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ignored_genes', models.CharField(blank=True, default='', max_length=500)),
                ('ignored_mutations', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.RenameModel(
            old_name='Filter',
            new_name='AleExperimentFilter',
        ),
    ]
