# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-16 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0002_auto_20160816_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalfilter',
            name='max_cutoff',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='globalfilter',
            name='min_cutoff',
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
