# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-17 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0003_auto_20160816_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalfilter',
            name='max_cutoff',
        ),
        migrations.RemoveField(
            model_name='globalfilter',
            name='min_cutoff',
        ),
    ]
