# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-24 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0004_auto_20160817_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalfilter',
            name='ignored_mutations',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
