# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-24 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0005_auto_20160824_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aleexperimentfilter',
            name='ignored_mutations',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
