# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-01 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0006_auto_20160824_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='aleexperimentfilter',
            name='starting_strain_mutations',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
