# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-23 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0007_aleexperimentfilter_starting_strain_mutations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aleexperimentfilter',
            name='ignored_genes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
