# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0008_auto_20181016_1137'),
        ('filter', '0008_auto_20181023_1035'),
    ]

    operations = [
    ]
