# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-18 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0009_merge_20181029_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aleexperimentfilter',
            name='ignored_mutations',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='aleexperimentfilter',
            name='starting_strain_mutations',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='globalfilter',
            name='ignored_genes',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='globalfilter',
            name='ignored_mutations',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
