# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-09-02 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0010_auto_20200517_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='aleexperimentfilter',
            name='max_gatk_cutoff',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='aleexperimentfilter',
            name='min_gatk_cutoff',
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
