# Generated by Django 4.2.30 on 2026-06-26 18:19

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mut_needle_data', jsonfield.fields.JSONField(default=dict)),
                ('histogram_data', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
