# Generated by Django 4.2.30 on 2026-08-23 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aledb_stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticdata',
            name='histogram_data',
        ),
    ]
