# Generated by Django 4.2.30 on 2026-08-26 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aledb_experiment', '0003_backfill_view_project_grants'),
        ('aledb_stats', '0002_remove_staticdata_histogram_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentSummary',
            fields=[
                ('ale_experiment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='summary', serialize=False, to='aledb_experiment.aleexperiment')),
                ('mutation_type_counts', models.JSONField(default=dict)),
                ('observed_mutation_type_counts', models.JSONField(default=dict)),
                ('protein_change_counts', models.JSONField(default=dict)),
                ('observed_protein_change_counts', models.JSONField(default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'experiment summaries',
            },
        ),
    ]
