# Generated by Django 4.2.30 on 2026-06-26 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aledb_experiment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.TextField()),
                ('ale_experiment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aledb_experiment.aleexperiment')),
            ],
        ),
    ]
