# Generated by Django 6.1.1 on 2026-09-04 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aledb_bibliome', '0001_initial'),
        ('aledb_experiment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aledb_experiment.experiment'),
        ),
    ]
