# Generated by Django 6.1.1 on 2026-09-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population_count', models.IntegerField(default=0)),
                ('time_point_count', models.IntegerField(default=0)),
                ('sample_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MutationCallCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('single_base_substitution', models.IntegerField(default=0)),
                ('multiple_base_substitution', models.IntegerField(default=0)),
                ('deletion', models.IntegerField(default=0)),
                ('insertion', models.IntegerField(default=0)),
                ('mobile_element_insertion', models.IntegerField(default=0)),
                ('amplification', models.IntegerField(default=0)),
                ('gene_conversion', models.IntegerField(default=0)),
                ('inversion', models.IntegerField(default=0)),
                ('intergenic', models.IntegerField(default=0)),
                ('noncoding', models.IntegerField(default=0)),
                ('pseudogene', models.IntegerField(default=0)),
                ('synonymous', models.IntegerField(default=0)),
                ('nonsynonymous', models.IntegerField(default=0)),
                ('nonsense', models.IntegerField(default=0)),
                ('unannotated', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueMutationCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('single_base_substitution', models.IntegerField(default=0)),
                ('multiple_base_substitution', models.IntegerField(default=0)),
                ('deletion', models.IntegerField(default=0)),
                ('insertion', models.IntegerField(default=0)),
                ('mobile_element_insertion', models.IntegerField(default=0)),
                ('amplification', models.IntegerField(default=0)),
                ('gene_conversion', models.IntegerField(default=0)),
                ('inversion', models.IntegerField(default=0)),
                ('intergenic', models.IntegerField(default=0)),
                ('noncoding', models.IntegerField(default=0)),
                ('pseudogene', models.IntegerField(default=0)),
                ('synonymous', models.IntegerField(default=0)),
                ('nonsynonymous', models.IntegerField(default=0)),
                ('nonsense', models.IntegerField(default=0)),
                ('unannotated', models.IntegerField(default=0)),
            ],
        ),
    ]
