# Generated by Django 6.1.1 on 2026-09-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name_plural': 'installation counts',
            },
        ),
    ]
