# Generated by Django 4.2.30 on 2026-06-26 18:19

from django.db import migrations, models
import jsonfield.fields


def bar_chart_json_default():
    """The default BarCharts was created with, kept local to this migration.

    It used to live on the model. BarCharts is deleted in 0002 and the callable
    went with it, but a historical migration may not reference code that no longer
    exists -- importing this module would raise AttributeError. Nothing calls it:
    the table is created here and dropped later.
    """
    return {"": ""}


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarCharts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mut_gene_json', jsonfield.fields.JSONField(default=bar_chart_json_default)),
                ('mut_json', jsonfield.fields.JSONField(default=bar_chart_json_default)),
            ],
        ),
        migrations.CreateModel(
            name='ObservedMutationCounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('single_base_substitution', models.IntegerField(default=0)),
                ('multiple_base_substitution', models.IntegerField(default=0)),
                ('deletion', models.IntegerField(default=0)),
                ('insertion', models.IntegerField(default=0)),
                ('mobile_element_insertion', models.IntegerField(default=0)),
                ('amplification', models.IntegerField(default=0)),
                ('gene_conversion', models.IntegerField(default=0)),
                ('inversion', models.IntegerField(default=0)),
                ('intergenic', models.IntegerField(default=0)),
                ('noncoding', models.IntegerField(default=0)),
                ('pseudogene', models.IntegerField(default=0)),
                ('synonymous', models.IntegerField(default=0)),
                ('nonsynonymous', models.IntegerField(default=0)),
                ('unannotated', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SampleCounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ale_count', models.IntegerField(default=0)),
                ('isolate_count', models.IntegerField(default=0)),
                ('flask_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('icon', models.CharField(max_length=200)),
                ('color', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueMutationCounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('single_base_substitution', models.IntegerField(default=0)),
                ('multiple_base_substitution', models.IntegerField(default=0)),
                ('deletion', models.IntegerField(default=0)),
                ('insertion', models.IntegerField(default=0)),
                ('mobile_element_insertion', models.IntegerField(default=0)),
                ('amplification', models.IntegerField(default=0)),
                ('gene_conversion', models.IntegerField(default=0)),
                ('inversion', models.IntegerField(default=0)),
                ('intergenic', models.IntegerField(default=0)),
                ('noncoding', models.IntegerField(default=0)),
                ('pseudogene', models.IntegerField(default=0)),
                ('synonymous', models.IntegerField(default=0)),
                ('nonsynonymous', models.IntegerField(default=0)),
                ('unannotated', models.IntegerField(default=0)),
            ],
        ),
    ]
