# Generated by Django 4.2.30 on 2026-06-26 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aledb_experiment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ignored_genes', models.CharField(blank=True, default='', max_length=15000)),
                ('ignored_mutations', models.CharField(blank=True, default='', max_length=15000)),
            ],
        ),
        migrations.CreateModel(
            name='AleExperimentFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_cutoff', models.PositiveSmallIntegerField(default=20)),
                ('max_cutoff', models.PositiveSmallIntegerField(default=100)),
                ('min_gatk_cutoff', models.PositiveSmallIntegerField(default=20)),
                ('max_gatk_cutoff', models.PositiveSmallIntegerField(default=100)),
                ('ignored_genes', models.TextField(blank=True, default='')),
                ('ignored_mutations', models.CharField(blank=True, default='', max_length=15000)),
                ('starting_strain_mutations', models.CharField(blank=True, default='', max_length=15000)),
                ('ale_experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aledb_experiment.aleexperiment')),
            ],
        ),
    ]
