"""Drop `min_gatk_cutoff` and `max_gatk_cutoff`.

No form, view or template ever exposed either, so every row in every deployment sat at the
defaults; their only effect was to switch on the `frequency_gatk` terms that made the real
cutoffs filter nothing. `aledb_seq.0011` removes the column they compared against.
"""


# Generated by Django 4.2.30 on 2026-08-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aledb_filter', '0003_drop_hidden_mutation_lists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aleexperimentfilter',
            name='max_gatk_cutoff',
        ),
        migrations.RemoveField(
            model_name='aleexperimentfilter',
            name='min_gatk_cutoff',
        ),
    ]
