# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seq', '0004_delete_genetopdb'),
        ('ale', '0012_auto_20160728_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotGeneMutation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ale_experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ale.AleExperiment')),
                ('mutation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seq.Mutation')),
            ],
        ),
    ]
