# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrichment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HotGeneMutation',
            new_name='EnrichmentMutation',
        ),
    ]
