__author__ = "Patrick Phaneuf"

REQUEST_ALL = "all"
REQUEST_MUTATION_ID = "mutation_id"
REQUEST_ALE_EXPERIMENT_ID = "ale_experiment_id"
REQUEST_ALE_ID = "ale_no"
POSITION_COLUMN_IN_REGULAR_MUTATION_TABLE = 2
POSITION_COLUMN_IN_SHARED_MUTATION_TALBE = 3
