"""One sample's mutations, laid out the way breseq's own report lays them out.

`/mutations` pivots an experiment across every sample, which is what you want for
comparing lineages and not what you want for reading one sample. This is the other
view of the same data: a single resequencing run in breseq's column order and
coloring, with a picker to move between samples.

It renders server-side rather than feeding DataTables a JSON blob, because the
cell markup *is* breseq's -- generated by `mutint_import.annotate.display`, which
is the same code that produced the HTML in the breseq report the sample came from.
"""

import collections
import logging
import time

from django.http import HttpResponse
from django.template import loader
from django.urls import reverse

import mutint_sample.views.common
from mutint_common.logger import join_extras, user_extra
from mutint_common.preferences import get_preference
from mutint_common.util import get_user_context
from mutint_experiment.models import Experiment
from mutint_experiment.permissions import can_edit_project
from mutint_filter.util import filter_mutation_calls
from mutint_filter.view_filter import get_view_filter
from mutint_sample.breseq_report import build_rows, is_mixed
from mutint_sample.models import ReferenceSequences, MutationCall
from mutint_sample.mutation_matrix import REFERENCES_PREFERENCE_PREFIX
from mutint_experiment.ancestor import (ancestral_mutation_ids, ancestral_shown,
                                        describe_ancestor)
from mutint_sample.util import get_ordered_sample_dict

logger = logging.getLogger(__name__)

REQUEST_SAMPLE_ID = "sample_id"


def breseq_table(request):
    context = get_user_context(request.user)
    try:
        started = time.time()
        experiment = mutint_sample.views.common.get_experiment(request)
        population = mutint_sample.views.common.get_population(request)
        sample_type = mutint_sample.views.common.get_sample_type(request)

        # `include_ancestor=True`, unlike every other reading page. This one shows a single
        # sample at a time, so there is nothing here for an ancestral mutation to contaminate
        # -- and hiding the ancestor from the only picker that could reach it made it
        # unreachable rather than merely excluded. It is listed first and tinted; the
        # analyses that aggregate across samples still leave it out.
        sample_dict = get_ordered_sample_dict(experiment.id, population,
                                            sample_type, include_ancestor=True)
        sample_dict = _ancestor_first(sample_dict, experiment.ancestor_id)
        sample = _selected_sample(request, sample_dict, experiment)
        is_ancestor = sample is not None and sample.id == experiment.ancestor_id

        view_filter = get_view_filter(request, experiment.id)
        # Resolved once for the whole page: the tint is a membership test per rendered row.
        ancestral_ids = ancestral_mutation_ids(experiment.id)
        # The reader's choice, remembered per experiment and shared with Compare. The
        # ancestor's own page shows its rows whatever the choice says: they are all it has.
        shown = ancestral_shown(request, experiment.id)
        rows, ancestral_count = (
            _rows_for(experiment, sample, view_filter, ancestral_ids,
                      show_ancestral=shown or is_ancestor)
            if sample is not None else ([], 0))

        context.update(experiment.experiment_context())
        context.update({
            "population_names": mutint_sample.views.common.get_population_names(experiment.id),
            "population": population,
            "experiment_name": experiment.name,
            "sample_type": sample_type,
            "sample_list": list(sample_dict.values()),
            "selected_sample": sample,
            "selected_sample_id": sample.id if sample is not None else None,
            "is_mixed": is_mixed(sample),
            "is_ancestor": is_ancestor,
            "ancestral_shown": shown,
            # Counted before the toggle drops them, so the Show button can say how many.
            "ancestral_count": ancestral_count,
            # The name and pk, so the legend can link the tinted rows to the sample they
            # came from. `describe_ancestor` is what the summary line under every other
            # table already uses, rather than a second way of spelling the same thing.
            "ancestor": describe_ancestor(experiment.id),
            "rows": rows,
            "unannotated_count": sum(1 for row in rows if not row["annotated"]),
            # The References menu: the contigs this sample's rows are on, and the reader's
            # remembered choice -- the matrix's own key, so Compare and this page agree.
            "seq_ids": sorted({row["seq_id_text"] for row in rows if row["seq_id_text"]}),
            "embedded_preferences": _embedded_preferences(request.user, experiment.id),
            "preferences_url": reverse("preferences"),
            "reference": _reference(experiment),
            "title": "%s mutations" % experiment.name,
            "template_header": "Mutations",
            # Whether to offer the breseq report links. The flag rather than a stat: this renders
        # on every view of the page.
        "report_stored": bool(sample is not None and sample.report_stored),
        "can_edit": can_edit_project(request.user, experiment.project),
        })

        logger.info("samples",
                    extra=join_extras(user_extra(request),
                                      {"time taken": time.time() - started, "rows": len(rows)}))
        template = loader.get_template("breseq_table/breseq_table.html")
        return HttpResponse(template.render(context, request), content_type="text/html")
    except Experiment.DoesNotExist:
        return mutint_sample.views.common.no_experiment_selected(
            request, context, logger, "samples")
    except Exception as error:
        logger.exception("samples broke", extra=user_extra(request))
        context["err_message"] = str(error)
        template = loader.get_template("500.html")
        return HttpResponse(template.render(context, request), content_type="text/html")


#: The tab the reader left open on this page, remembered by mutint_control_tabs.js.
TAB_PREFERENCE_KEY = "breseq_table.tab"


def _embedded_preferences(user, experiment_id):
    """`{key: value}` for the two preferences this page embeds, each only when stored.

    The same shape the matrix embeds its whole prefix in, so the scripts read them through
    the same `get(key)`; named keys rather than a prefix, because this page has one experiment
    and one strip.
    """
    if not getattr(user, "is_authenticated", False):
        return {}
    embedded = {}
    for key in (REFERENCES_PREFERENCE_PREFIX + str(experiment_id), TAB_PREFERENCE_KEY):
        stored = get_preference(user, key)
        if stored is not None:
            embedded[key] = stored
    return embedded


def _ancestor_first(sample_dict, ancestor_id):
    """Move the designated ancestor to the top of the picker.

    It is what the other samples are read against, so it belongs at the top rather than
    wherever A/F/I/R ordering happens to put it -- for the LTEE that is a lucky first anyway,
    but only because its ancestor is filed under an ALE that sorts early.

    Order only. The *default* selection stays the first non-ancestor sample (see
    `_selected_sample`), so opening Mutations still lands on evolved data.
    """
    if ancestor_id is None or ancestor_id not in sample_dict:
        return sample_dict
    ordered = collections.OrderedDict()
    ordered[ancestor_id] = sample_dict[ancestor_id]
    for key, value in sample_dict.items():
        if key != ancestor_id:
            ordered[key] = value
    return ordered


def _selected_sample(request, sample_dict, experiment):
    """The requested sample; failing that the first one that is not the ancestor.

    The ancestor is listed, and listed first, but is not what the page opens on: this view is
    read as "what evolved in this sample", and defaulting to the one sample where the answer
    is "nothing, by definition" is a poor first thing to show. It is one click away in the
    picker, which is the point of putting it there.

    The lookup still falls back to a scoped query. `sample_dict` honours the ALE, sample-type
    and tag filters, so a requested id can legitimately be missing from it -- and without the
    fallback a link to a filtered-out sample would quietly render a *different* one, which is
    the worst available outcome because the page would look entirely normal while showing the
    wrong thing. Scoped to the experiment, so it is not a way around anything.
    """
    requested = request.GET.get(REQUEST_SAMPLE_ID)
    if requested:
        try:
            sample_id = int(requested)
        except (TypeError, ValueError):
            sample_id = None
        if sample_id in sample_dict:
            return sample_dict[sample_id]
        if sample_id is not None:
            hidden = get_ordered_sample_dict(experiment.id, include_ancestor=True)
            if sample_id in hidden:
                return hidden[sample_id]
    for sample in sample_dict.values():
        if sample.id != experiment.ancestor_id:
            return sample
    # An experiment whose only sample is the ancestor: show it rather than nothing.
    for sample in sample_dict.values():
        return sample
    return None


def _rows_for(experiment, sample, view_filter=None, ancestral_ids=frozenset(), *,
              show_ancestral=False):
    """This sample's rows, and how many of them the designated ancestor also carries.

    The raw call queryset, through the reader's filter. What happens to the ancestral calls
    is the reader's other choice: hidden they are dropped here, before `build_rows`, because
    breseq stripes by row index and a row hidden afterwards would leave two neighbours the
    same shade; shown they stay, and `build_rows` tints them. The count is taken before the
    drop, so the Show button can say what it would reveal.

    In Python rather than by `.exclude(mutation_id__in=...)`: the set is already in hand for
    the tint, and `ancestral_mutation_ids` says why it should not go back to the database.
    """
    call = filter_mutation_calls(
        MutationCall.objects.filter(sample=sample).select_related("mutation"),
        view_filter=view_filter)
    # filter_mutation_calls orders across samples; within one sample breseq
    # orders by reference then position.
    call.sort(key=lambda o: (o.mutation.seq_id or "", o.mutation.start_position))
    ancestral_count = sum(1 for o in call if o.mutation_id in ancestral_ids)
    if not show_ancestral:
        call = [o for o in call if o.mutation_id not in ancestral_ids]
    rows = build_rows(call, browse_url=_browse_url(sample),
                      ancestral_mutation_ids=ancestral_ids,
                      refseq_url=_refseq_url())
    return rows, ancestral_count


def _browse_url(sample):
    """Link the evidence cell at the alignment, when there is one to look at."""
    if not sample.bam_stored:
        return None
    return lambda call: "%s?mutation_call_id=%s" % (
        reverse("browse_mutation"), call.id)


def _refseq_url():
    """Link the Reference cell at that contig's entry in NCBI's annotation.

    Takes no experiment lookup and makes no query: whether the contig has been matched to
    an NCBI record decides what that page *shows*, not whether it is worth opening.
    """
    def url_for(call):
        if not call.mutation.seq_id:
            return None
        return "%s?mutation_id=%s&sample_id=%s" % (
            reverse("ncbi_view"), call.mutation_id, call.sample_id)

    return url_for


def _reference(experiment):
    return ReferenceSequences.objects.filter(experiment=experiment).first()
