"""One sample's mutations, laid out the way breseq's own report lays them out.

`/mutations` pivots an experiment across every sample, which is what you want for
comparing lineages and not what you want for reading one sample. This is the other
view of the same data: a single resequencing run in breseq's column order and
coloring, with a picker to move between samples.

It renders server-side rather than feeding DataTables a JSON blob, because the
cell markup *is* breseq's -- generated by `mutint_import.annotate.display`, which
is the same code that produced the HTML in the breseq report the sample came from.
"""

import collections
import logging
import time

from django.http import HttpResponse
from django.template import loader
from django.urls import reverse

import mutint_sample.views.common
from mutint_common.logger import join_extras, user_extra
from mutint_common.util import get_user_context
from mutint_experiment.models import Experiment
from mutint_experiment.permissions import can_edit_project
from mutint_filter.util import filter_mutation_calls
from mutint_filter.view_filter import get_view_filter
from mutint_sample.breseq_report import build_rows, is_mixed
from mutint_sample.models import ReferenceSequences, MutationCall
from mutint_experiment.ancestor import ancestral_mutation_ids, describe_ancestor
from mutint_sample.util import get_ordered_sample_dict

logger = logging.getLogger(__name__)

REQUEST_SAMPLE_ID = "sample_id"


def breseq_table(request):
    context = get_user_context(request.user)
    try:
        started = time.time()
        experiment = mutint_sample.views.common.get_experiment(request)
        population = mutint_sample.views.common.get_population(request)
        sample_type = mutint_sample.views.common.get_sample_type(request)

        # `include_ancestor=True`, unlike every other reading page. This one shows a single
        # sample at a time, so there is nothing here for an ancestral mutation to contaminate
        # -- and hiding the ancestor from the only picker that could reach it made it
        # unreachable rather than merely excluded. It is listed first and tinted; the
        # analyses that aggregate across samples still leave it out.
        sample_dict = get_ordered_sample_dict(experiment.id, population,
                                            sample_type, include_ancestor=True)
        sample_dict = _ancestor_first(sample_dict, experiment.ancestor_id)
        sample = _selected_sample(request, sample_dict, experiment)

        view_filter = get_view_filter(request, experiment.id)
        # Resolved once for the whole page: the tint is a membership test per rendered row.
        ancestral_ids = ancestral_mutation_ids(experiment.id)
        rows = (_rows_for(experiment, sample, view_filter, ancestral_ids)
                if sample is not None else [])

        context.update(experiment.experiment_context())
        context.update({
            "population_names": mutint_sample.views.common.get_population_names(experiment.id),
            "population": population,
            "experiment_name": experiment.name,
            "project_name": experiment.project.name if experiment.project else "",
            "project_id": experiment.project_id,
            "sample_type": sample_type,
            "sample_list": list(sample_dict.values()),
            "selected_sample": sample,
            "selected_sample_id": sample.id if sample is not None else None,
            "is_mixed": is_mixed(sample),
            "is_ancestor": sample is not None and sample.id == experiment.ancestor_id,
            "ancestral_count": sum(1 for row in rows if row["ancestral"]),
            # The name and pk, so the legend can link the tinted rows to the sample they
            # came from. `describe_ancestor` is what the summary line under every other
            # table already uses, rather than a second way of spelling the same thing.
            "ancestor": describe_ancestor(experiment.id),
            "rows": rows,
            "unannotated_count": sum(1 for row in rows if not row["annotated"]),
            "reference": _reference(experiment),
            "title": "%s mutations" % experiment.name,
            "template_header": "Mutations",
            # Whether to offer the breseq report links. The flag rather than a stat: this renders
        # on every view of the page.
        "report_stored": bool(sample is not None and sample.report_stored),
        "can_edit": can_edit_project(request.user, experiment.project),
        })

        logger.info("samples",
                    extra=join_extras(user_extra(request),
                                      {"time taken": time.time() - started, "rows": len(rows)}))
        template = loader.get_template("breseq_table/breseq_table.html")
        return HttpResponse(template.render(context, request), content_type="text/html")
    except Experiment.DoesNotExist:
        return mutint_sample.views.common.no_experiment_selected(
            request, context, logger, "samples")
    except Exception as error:
        logger.exception("samples broke", extra=user_extra(request))
        context["err_message"] = str(error)
        template = loader.get_template("500.html")
        return HttpResponse(template.render(context, request), content_type="text/html")


def _ancestor_first(sample_dict, ancestor_id):
    """Move the designated ancestor to the top of the picker.

    It is what the other samples are read against, so it belongs at the top rather than
    wherever A/F/I/R ordering happens to put it -- for the LTEE that is a lucky first anyway,
    but only because its ancestor is filed under an ALE that sorts early.

    Order only. The *default* selection stays the first non-ancestor sample (see
    `_selected_sample`), so opening Mutations still lands on evolved data.
    """
    if ancestor_id is None or ancestor_id not in sample_dict:
        return sample_dict
    ordered = collections.OrderedDict()
    ordered[ancestor_id] = sample_dict[ancestor_id]
    for key, value in sample_dict.items():
        if key != ancestor_id:
            ordered[key] = value
    return ordered


def _selected_sample(request, sample_dict, experiment):
    """The requested sample; failing that the first one that is not the ancestor.

    The ancestor is listed, and listed first, but is not what the page opens on: this view is
    read as "what evolved in this sample", and defaulting to the one sample where the answer
    is "nothing, by definition" is a poor first thing to show. It is one click away in the
    picker, which is the point of putting it there.

    The lookup still falls back to a scoped query. `sample_dict` honours the ALE, sample-type
    and tag filters, so a requested id can legitimately be missing from it -- and without the
    fallback a link to a filtered-out sample would quietly render a *different* one, which is
    the worst available outcome because the page would look entirely normal while showing the
    wrong thing. Scoped to the experiment, so it is not a way around anything.
    """
    requested = request.GET.get(REQUEST_SAMPLE_ID)
    if requested:
        try:
            sample_id = int(requested)
        except (TypeError, ValueError):
            sample_id = None
        if sample_id in sample_dict:
            return sample_dict[sample_id]
        if sample_id is not None:
            hidden = get_ordered_sample_dict(experiment.id, include_ancestor=True)
            if sample_id in hidden:
                return hidden[sample_id]
    for sample in sample_dict.values():
        if sample.id != experiment.ancestor_id:
            return sample
    # An experiment whose only sample is the ancestor: show it rather than nothing.
    for sample in sample_dict.values():
        return sample
    return None


def _rows_for(experiment, sample, view_filter=None, ancestral_ids=frozenset()):
    """This sample's rows, ancestor included.

    Deliberately the raw call queryset. Every page that analyzes the data subtracts the
    designated ancestor; this one tints those rows instead, because it is a view of what
    breseq called in one sample rather than a conclusion drawn from it.
    """
    call = filter_mutation_calls(
        MutationCall.objects.filter(sample=sample).select_related("mutation"),
        view_filter=view_filter)
    # filter_mutation_calls orders across samples; within one sample breseq
    # orders by reference then position.
    call.sort(key=lambda o: (o.mutation.seq_id or "", o.mutation.start_position))
    return build_rows(call, browse_url=_browse_url(sample),
                      ancestral_mutation_ids=ancestral_ids,
                      refseq_url=_refseq_url())


def _browse_url(sample):
    """Link the evidence cell at the alignment, when there is one to look at."""
    if not sample.bam_stored:
        return None
    return lambda call: "%s?mutation_call_id=%s" % (
        reverse("browse_mutation"), call.id)


def _refseq_url():
    """Link the Reference cell at that contig's entry in NCBI's annotation.

    Takes no experiment lookup and makes no query: whether the contig has been matched to
    an NCBI record decides what that page *shows*, not whether it is worth opening.
    """
    def url_for(call):
        if not call.mutation.seq_id:
            return None
        return "%s?mutation_id=%s&sample_id=%s" % (
            reverse("ncbi_view"), call.mutation_id, call.sample_id)

    return url_for


def _reference(experiment):
    return ReferenceSequences.objects.filter(experiment=experiment).first()
