# Generated by Django 6.1.1 on 2026-09-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MutationEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('add', 'Added'), ('remove', 'Removed')], max_length=10)),
                ('snapshot', models.JSONField(default=dict)),
                ('mutation_identity', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='MutationEditSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('kind', models.CharField(choices=[('delete', 'Delete'), ('copy', 'Copy'), ('add', 'Add'), ('edit', 'Edit'), ('restore', 'Restore')], max_length=20)),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
