# Generated by Django 6.1.1 on 2026-09-06 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mutint_curate', '0001_initial'),
        ('mutint_experiment', '0001_initial'),
        ('mutint_sample', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mutationedit',
            name='mutation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mutint_sample.mutation'),
        ),
        migrations.AddField(
            model_name='mutationedit',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mutint_sample.sample'),
        ),
        migrations.AddField(
            model_name='mutationedit',
            name='source_sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mutint_sample.sample'),
        ),
        migrations.AddField(
            model_name='mutationeditset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mutationeditset',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutation_edit_sets', to='mutint_experiment.experiment'),
        ),
        migrations.AddField(
            model_name='mutationeditset',
            name='restored_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restorations', to='mutint_curate.mutationeditset'),
        ),
        migrations.AddField(
            model_name='mutationedit',
            name='edit_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='mutint_curate.mutationeditset'),
        ),
    ]
