# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-19 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixatedmutation',
            name='fixed_observed_mutation_series',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
