# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-05 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixation', '0002_fixatedmutation_fixed_observed_mutation_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixatedmutation',
            name='fixed_observed_mutation_series',
            field=models.TextField(default='', null=True),
        ),
    ]
