# Generated by Django 6.1.1 on 2026-09-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutint_sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutationcall',
            name='supplemental_data',
            field=models.JSONField(default=dict),
        ),
    ]
