# Generated by Django 6.1.1 on 2026-09-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutint_sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='treatment',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
