# Generated by Django 6.1.1 on 2026-09-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aledb_sample', '0002_mutationcall_supplemental_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='report_stored',
            field=models.BooleanField(default=False),
        ),
    ]
